index: "dolphin-stage-1"
load_path: "dolphin-stage-0"
dataset:
  path: "./data/dolphin/end/"
  factor: 2
  patches:
    height: 80
    width: 80
geoms:
  background:
    constant: 3.0
training:
  steps: 40000
  prune_steps: 0
  prune_start: 0
  prune_stop: 0
  add_steps: 0
  add_start: 0
  add_stop: 0
  add_num: 0
  fix_keys: [
    # "points",
    "attn",
    "pc_feats",
    "renderer",
    "points_influ_scores"
  ]
  lr:
    points:
      type: "multistep"
      base_lr: 7.5e-3
      warmup: 20000
      gamma: 5.0e-2
  regularizers:
    num_nn: 200 # higher value increases the rigidity of the moving parts during interpolation
    weight: 5.0
    ldas_steps: 100
eval:
  dataset:
    path: "./data/dolphin/end/"
    factor: 2
  img_idx: 27
test:
  datasets:
    - name: "testset"
      path: "./data/dolphin/end/"
      factor: 2