index: "lamp-stage-0"
dataset:
  path: "./data/lamp/start/"
  factor: 2
geoms:
  points:
    init_scale: [1.1, 1.1, 1.1]
  background:
    constant: 3.0
eval:
  dataset:
    path: "./data/lamp/start/"
    factor: 2
test:
  datasets:
    - name: "testset"
      path: "./data/lamp/start/"
      factor: 2