index: "lamp-stage-2"
load_path: "lamp-stage-1"
dataset:
  path: "./data/lamp/end/"
  factor: 2
geoms:
  background:
    constant: 3.0
training:
  steps: 40000
  prune_steps: 0
  prune_start: 0
  prune_stop: 0
  add_steps: 0
  add_start: 0
  add_stop: 0
  add_num: 0
  fix_keys: [
    "points",
    # "attn",
    # "pc_feats",
    "renderer",
    "points_influ_scores"
  ]
  lr:
    attn:
      type: "none"
      base_lr: 3.0e-4
      warmup: 0
    feats:
      type: "none"
      base_lr: 5.0e-3
      warmup: 0
eval:
  dataset:
    path: "./data/lamp/end/"
    factor: 2
  img_idx: 199
test:
  datasets:
    - name: "testset"
      path: "./data/lamp/end/"
      factor: 2